#url do postgre se fosse o mySQL poderia colocar ?creatDatavaseIfNotExists=true e criaria a tabela
#  DB_HOST E DB_NAME são variáveis de ambiente que foram criadas com o nome do host e o nome do banco de dados
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5433/${DB_NAME}
#login e senha DB_USER E DB_PASSWORD USUARIO E SENHAS SALVAS NUMA VARIÁVEL DE AMBIENTE
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
#driver que o postgre usa e o dialeto do hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
#hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# indica que quando eu rodar a minha aplicação se alguma coisa na classe for alterada, no banco tbm será alterado
spring.jpa.hibernate.ddl-auto=update
#mostra o que esta sendo feito no banco, o que a JPA está fazendo
spring.jpa.show-sql=true
#ver tudo formatado no log
spring.jpa.format-sql=true